######################################################################
# Automatically generated by qmake (3.1) Tue Apr 8 10:30:16 2025
######################################################################
QT += widgets   # Required for QMainWindow

TEMPLATE = app
TARGET = RGB888Player
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += mainwindow.h \
           globals.h \
           transcodethread.h \
           ffmpeg/include/libavcodec/avcodec.h \
           ffmpeg/include/libavcodec/avfft.h \
           ffmpeg/include/libavcodec/dv_profile.h \
           ffmpeg/include/libavcodec/dxva2.h \
           ffmpeg/include/libavcodec/old_codec_ids.h \
           ffmpeg/include/libavcodec/vaapi.h \
           ffmpeg/include/libavcodec/vda.h \
           ffmpeg/include/libavcodec/vdpau.h \
           ffmpeg/include/libavcodec/version.h \
           ffmpeg/include/libavcodec/vorbis_parser.h \
           ffmpeg/include/libavcodec/xvmc.h \
           ffmpeg/include/libavdevice/avdevice.h \
           ffmpeg/include/libavdevice/version.h \
           ffmpeg/include/libavfilter/asrc_abuffer.h \
           ffmpeg/include/libavfilter/avcodec.h \
           ffmpeg/include/libavfilter/avfilter.h \
           ffmpeg/include/libavfilter/avfiltergraph.h \
           ffmpeg/include/libavfilter/buffersink.h \
           ffmpeg/include/libavfilter/buffersrc.h \
           ffmpeg/include/libavfilter/version.h \
           ffmpeg/include/libavformat/avformat.h \
           ffmpeg/include/libavformat/avio.h \
           ffmpeg/include/libavformat/version.h \
           ffmpeg/include/libavutil/adler32.h \
           ffmpeg/include/libavutil/aes.h \
           ffmpeg/include/libavutil/attributes.h \
           ffmpeg/include/libavutil/audio_fifo.h \
           ffmpeg/include/libavutil/audioconvert.h \
           ffmpeg/include/libavutil/avassert.h \
           ffmpeg/include/libavutil/avconfig.h \
           ffmpeg/include/libavutil/avstring.h \
           ffmpeg/include/libavutil/avutil.h \
           ffmpeg/include/libavutil/base64.h \
           ffmpeg/include/libavutil/blowfish.h \
           ffmpeg/include/libavutil/bprint.h \
           ffmpeg/include/libavutil/bswap.h \
           ffmpeg/include/libavutil/buffer.h \
           ffmpeg/include/libavutil/cast5.h \
           ffmpeg/include/libavutil/channel_layout.h \
           ffmpeg/include/libavutil/common.h \
           ffmpeg/include/libavutil/cpu.h \
           ffmpeg/include/libavutil/crc.h \
           ffmpeg/include/libavutil/dict.h \
           ffmpeg/include/libavutil/display.h \
           ffmpeg/include/libavutil/downmix_info.h \
           ffmpeg/include/libavutil/error.h \
           ffmpeg/include/libavutil/eval.h \
           ffmpeg/include/libavutil/ffversion.h \
           ffmpeg/include/libavutil/fifo.h \
           ffmpeg/include/libavutil/file.h \
           ffmpeg/include/libavutil/frame.h \
           ffmpeg/include/libavutil/hash.h \
           ffmpeg/include/libavutil/hmac.h \
           ffmpeg/include/libavutil/imgutils.h \
           ffmpeg/include/libavutil/intfloat.h \
           ffmpeg/include/libavutil/intreadwrite.h \
           ffmpeg/include/libavutil/lfg.h \
           ffmpeg/include/libavutil/log.h \
           ffmpeg/include/libavutil/lzo.h \
           ffmpeg/include/libavutil/macros.h \
           ffmpeg/include/libavutil/mathematics.h \
           ffmpeg/include/libavutil/md5.h \
           ffmpeg/include/libavutil/mem.h \
           ffmpeg/include/libavutil/motion_vector.h \
           ffmpeg/include/libavutil/murmur3.h \
           ffmpeg/include/libavutil/old_pix_fmts.h \
           ffmpeg/include/libavutil/opt.h \
           ffmpeg/include/libavutil/parseutils.h \
           ffmpeg/include/libavutil/pixdesc.h \
           ffmpeg/include/libavutil/pixelutils.h \
           ffmpeg/include/libavutil/pixfmt.h \
           ffmpeg/include/libavutil/random_seed.h \
           ffmpeg/include/libavutil/rational.h \
           ffmpeg/include/libavutil/replaygain.h \
           ffmpeg/include/libavutil/ripemd.h \
           ffmpeg/include/libavutil/samplefmt.h \
           ffmpeg/include/libavutil/sha.h \
           ffmpeg/include/libavutil/sha512.h \
           ffmpeg/include/libavutil/stereo3d.h \
           ffmpeg/include/libavutil/threadmessage.h \
           ffmpeg/include/libavutil/time.h \
           ffmpeg/include/libavutil/timecode.h \
           ffmpeg/include/libavutil/timestamp.h \
           ffmpeg/include/libavutil/version.h \
           ffmpeg/include/libavutil/xtea.h \
           ffmpeg/include/libpostproc/postprocess.h \
           ffmpeg/include/libpostproc/version.h \
           ffmpeg/include/libswresample/swresample.h \
           ffmpeg/include/libswresample/version.h \
           ffmpeg/include/libswscale/swscale.h \
           ffmpeg/include/libswscale/version.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp transcodethread.cpp \
    globals.cpp




